[package]
name = "image_files"
version = "0.9.3"
edition = "2021"
authors = ["Evan Raeder"]

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
image = "0.25.1"
indicatif = "0.17.8"

[build-dependencies]
winres = "0.1"
